swagger: '2.0'
info:
  version: '1.0.0'
  title: "Token API"
  description: "API to generate an Access Token"
schemes:
  - "https"
securityDefinitions:
  basicAuth:
    type: "basic"
host: "card.api.fiservapps.com"
security:
  - basicAuth: []
basePath: "/cs/oauth2"
paths:
  /token:
    post:
      tags:
      - Token
      x-child-product-name: Token
      x-proxy-name: Token
      x-group-name: Token 1.0.0
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      summary: "API to generate an access token."
      parameters:
        - name: "x-fapi-financial-id"
          in: "header"
          description: "Enter the client id"
          required: true
          type: "string"
          pattern: "^[0-9]*$"
          minLength: 8
          maxLength: 8
        - name: "x-fapi-interaction-id"
          in: "header"
          description: "Enter the transaction/correlation id"
          required: false
          type: "string"
          pattern: "^[^-][a-zA-Z0-9-][^-]$"
          minLength: 15
          maxLength: 40          
        - name: "code_challenge"
          description:  "REQUIRED for Mobile app clients ONLY. To be generated by client code using a code_verifier and code_challenge_method."
          in: "header"
          required: false
          type: "string"
          maxLength: 48
        - name: "code_challenge_method"
          description:  "REQUIRED for Mobile app clients ONLY. To be provided by client code."
          in: "header"
          required: false
          type: "string"
          enum:
            [
            SHA256,
            SHA512
            ]
        - name: "scope"
          in: "query"
          required: true
          type: "string"
          
        - name: "grant_type"
          in: "formData"
          required: true
          type: 'string'
      responses:
        '200':
          description: "OK"
          headers:
            x-fapi-interaction-id:
              type: "string"
              description:  "Represents a transaction ID created with each request."
          schema:
            $ref: '#/definitions/tokenResponse'
        '400':
          description: "Bad Request"
          headers:
            x-fapi-interaction-id:
              type: "string"
              description:  "Represents a transaction ID created with each request."
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/ErrorResponse'
        '415':
          description: "Unsupported Media Type"
          headers:
            x-fapi-interaction-id:
              type: "string"
              description:  "Represents a transaction ID created with each request."
          schema:
            $ref: '#/definitions/ErrorResponse'    
        '429':
          description: "Too Many Requests"
          headers:
            x-fapi-interaction-id:
              type: "string"
              description:  "Represents a transaction ID created with each request."
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: "Internal Server Error"
          headers:
            x-fapi-interaction-id:
              type: "string"
              description:  "Represents a transaction ID created with each request."
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: "Unexpected Error"
          schema:
            $ref: '#/definitions/ErrorResponse'    
definitions:
  tokenRequest:
    type: "object"
    properties:
      grant_type:
        type: "string"
  tokenResponse:
    type: "object"
    properties:
      refresh_token_expires_in:
        type: "string"
        format: "utc-millisec"
      api_product_list:
        type: "string"
      api_product_list_json:
        type: "array"
        items:
          type: "string"
      organization_name:
        type: "string"
      token_type:
        type: "string"
      issued_at:
        type: "string"
        format: "utc-millisec"
      client_id:
        type: "string"
      access_token:
        type: "string"
      application_name:
        type: "string"
      scope:
        type: "string"
      expires_in:
        type: "string"
        format: "utc-millisec"
      refresh_count:
        type: "string"
        format: "utc-millisec"
      status:
        type: "string"
  ErrorResponse:
    type: "object"
    properties:
      errors:
        type: "array"
        items:
         $ref: "#/definitions/Error"
  Error:
    type: "object"
    properties:
      code:
        type: "string"
      description:
        type: "string"
